services:
  jenkins:
    image: keerthan04/jenkins-spring:01 
    container_name: jenkins
    ports:
      - 8080:8080
    user: root
    volumes:
      - jenkins-sonar:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-sonar

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - 9000:9000
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar-logs:/opt/sonarqube/logs
    networks:
      - jenkins-sonar

networks:
  jenkins-sonar:

volumes:
  jenkins-sonar:
  sonar_data:
  sonar-logs:
