pipeline {
    agent {
        docker {
            image 'keerthan04/jenkins-java:v1'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    stages {
        stage('Example') {
            steps {
                sh 'whoami'
            }
        }
    }
}