pipeline {
    agent {
        docker {
            image 'keerthan04/jenkins-java:v1'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    stages {
        stage('Build Stage') {
            steps {
                sh 'cd spring-boot-app && mvn clean package -DskipTests'
            }
        }
        stage('Test Stage') {
            steps {
                sh 'cd spring-boot-app && mvn test'
            }
        }
    }

}